package tablas;
// Generated 03-jun-2018 22:40:12 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name="categorias")

public class Categorias implements java.io.Serializable {

	@Id
	@Column(name="IdCategoria")
	private Integer idCategoria;
	
	@Column(name="NombreCategoria")
	private String nombreCategoria;
	
	@Column(name="SalarioBaseCategoria")
	private double salarioBaseCategoria;
	
	@Column(name="ComplementosCategoria")
	private double complementoCategoria;
	
	private Set trabajadorbbdds = new HashSet(0);

	public Categorias() {
	}

	public Categorias(String nombreCategoria, double salarioBaseCategoria, double complementoCategoria) {
		this.nombreCategoria = nombreCategoria;
		this.salarioBaseCategoria = salarioBaseCategoria;
		this.complementoCategoria = complementoCategoria;
	}

	public Categorias(String nombreCategoria, double salarioBaseCategoria, double complementoCategoria,
			Set trabajadorbbdds) {
		this.nombreCategoria = nombreCategoria;
		this.salarioBaseCategoria = salarioBaseCategoria;
		this.complementoCategoria = complementoCategoria;
		this.trabajadorbbdds = trabajadorbbdds;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombreCategoria() {
		return this.nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}

	public double getSalarioBaseCategoria() {
		return this.salarioBaseCategoria;
	}

	public void setSalarioBaseCategoria(double salarioBaseCategoria) {
		this.salarioBaseCategoria = salarioBaseCategoria;
	}

	public double getComplementoCategoria() {
		return this.complementoCategoria;
	}

	public void setComplementoCategoria(double complementoCategoria) {
		this.complementoCategoria = complementoCategoria;
	}

	public Set getTrabajadorbbdds() {
		return this.trabajadorbbdds;
	}

	public void setTrabajadorbbdds(Set trabajadorbbdds) {
		this.trabajadorbbdds = trabajadorbbdds;
	}

}
