package tablas;
// Generated 03-jun-2018 22:40:12 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trabajadorbbdd generated by hbm2java
 */

@Entity
@Table(name = "trabajadorbbdd")

public class Trabajadorbbdd implements java.io.Serializable {
	@Id
	@Column(name= "idTrabajador")
	private Integer idTrabajador;
	
	@Column(name= "IdCategoria")
	private Categorias categorias;
	
	@Column(name= "IdEmpresa")
	private Empresas empresas;
	
	@Column(name= "Nombre")
	private String nombre;
	
	@Column(name= "Apellido1")
	private String apellido1;
	
	@Column(name= "Apellido2")
	private String apellido2;
	
	@Column(name= "NIFNIE")
	private String nifnie;
	
	@Column(name= "email")
	private String email;
	
	@Column(name= "FechaAlta")
	private Date fechaAlta;
	@Column(name= "CodigoCuenta")
	private String codigoCuenta;
	
	@Column(name= "IBAN")
	private String iban;
	
	private Set nominas = new HashSet(0);

	public Trabajadorbbdd() {
	}

	public Trabajadorbbdd(Categorias categorias, Empresas empresas, String nombre, String apellido1, String nifnie) {
		this.categorias = categorias;
		this.empresas = empresas;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.nifnie = nifnie;
	}

	public Trabajadorbbdd(Categorias categorias, Empresas empresas, String nombre, String apellido1, String apellido2,
			String nifnie, String email, Date fechaAlta, String codigoCuenta, String iban, Set nominas) {
		this.categorias = categorias;
		this.empresas = empresas;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.nifnie = nifnie;
		this.email = email;
		this.fechaAlta = fechaAlta;
		this.codigoCuenta = codigoCuenta;
		this.iban = iban;
		this.nominas = nominas;
	}

	public Integer getIdTrabajador() {
		return this.idTrabajador;
	}

	public void setIdTrabajador(Integer idTrabajador) {
		this.idTrabajador = idTrabajador;
	}

	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getNifnie() {
		return this.nifnie;
	}

	public void setNifnie(String nifnie) {
		this.nifnie = nifnie;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getCodigoCuenta() {
		return this.codigoCuenta;
	}

	public void setCodigoCuenta(String codigoCuenta) {
		this.codigoCuenta = codigoCuenta;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public Set getNominas() {
		return this.nominas;
	}

	public void setNominas(Set nominas) {
		this.nominas = nominas;
	}

}
